api/urls.py
from django.urls import path, include
from api.models import CourseResource, CategoryResource
from tastypie.api import Api

api = Api(api_name='v1')
api.register(CourseResource())  # am inregistarat resurele
api.register(CategoryResource())

# dupa inregistrarea resurselor adresele vor fi urmattoarele
# api/v1/course
# api/v1/categories

# for POST, DELETE add header
# KEY: Authorization
# VALUE: ApiKey andrew:keyforuseerandrew1234567890

urlpatterns = [
    path('', include(api.urls), name='index')
]

base/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls')),  # includem toate marshuturile descrise din 'shop\urls.py'
    # toate vor fi accesible pe adresa 'shop/'
    # Aici putem sa zicem am concetat toate marshuturile din aplicatiea 'shop'

    path('api/', include('api.urls'))

]

shop/urls.py
from django.urls import path
from . import views  # '.' importam tat modulul sub numele 'views'

app_name = 'shop'
urlpatterns = [
    path('courses/', views.courses, name='courses'),
    path('course_selected/id=<int:course_id>', views.course_selected, name='course_selected'),
    path('category/', views.category, name='category'),
    path('category_selected/id=<int:category_id>', views.category_selected, name='category_selected')

]

api/models.py
from tastypie.resources import ModelResource
from shop.models import Course, Category
from tastypie.authorization import Authorization
from .authentication import CustomAuthentication


# /api/v1/courses
# /api/v1/categories

class CategoryResource(ModelResource):
    class Meta:
        queryset = Category.objects.all()
        resource_name = 'categories'
        allowed_methods = ['get']


class CourseResource(ModelResource):
    class Meta:
        queryset = Course.objects.all()
        resource_name = 'courses'
        allowed_methods = ['get', 'post', 'delete']
        excludes = ['reviews_qty', 'created_at']  # aici nscriim cimpurele care se nu fie transmise clientului
        authentication = CustomAuthentication()
        authorization = Authorization()

    def hydrate(self, bundle):
        bundle.obj.category_id = bundle.data['category_id']
        return bundle

    def dehydrate(self, bundle):
        bundle.data['category'] = bundle.obj.category
        bundle.data['category_id'] = bundle.obj.category_id
        return bundle

shop/models.py
from django.db import models
from django.utils import timezone


# Create your models here.
class Category(models.Model):
    title = models.CharField(max_length=255)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title  # adugam metoda magica ca sa vedem denumirea titlului in partea de admin


class Course(models.Model):
    title = models.CharField(max_length=300)
    price = models.FloatField()
    students_qty = models.IntegerField()
    reviews_qty = models.IntegerField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    # 'on_delete=models.CASCADE' cind Categoria se sterge, se sterge automat cursurile din categorie
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        # return str(self.id) + ' ' + str(self.title) + ' ' + str(self.price)
        return self.title

api/views.py
from django.shortcuts import render

# Create your views here.

shop/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404
from .models import Course  # din mapa curenta din 'models.py' importam variabila 'Course'
from .models import Category


# Create your views here.
def courses(request):
    courses = Course.objects.all()
    return render(request, 'shop/courses.html', {'courses': courses})
    # return HttpResponse(courses)
    # return HttpResponse(str(course) + '<br>' for course in courses)
    # return HttpResponse(''.join([str(course) + '<br>' for course in courses]))


def course_selected(request, course_id):
    # Varianta 1
    # try:
    #     course = Course.objects.get(pk=course_id)
    #     return render(request, 'shop/course_selected.html', {'course': course}) # avem acces la variabila 'course'
    # except Course.DoesNotExist:
    #     raise Http404()

    # Varianta 2
    courses = get_object_or_404(Course, pk=course_id)
    return render(request, 'shop/course_selected.html', {'course': courses})


def category(request):
    category = Category.objects.all()
    return render(request, 'shop/category.html', {'category': category})


def category_selected(request, category_id):
    courses = Course.objects.filter(category_id=category_id)
    return render(request, 'shop/category_selected.html', {'courses': courses})

shop/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-dark bg-dark">
        <div class="container">
            <a href="" class="navbar-brand">Courses Shop</a>

        </div>
    </nav>
    <main class="container">
        {% block content %}
        {% endblock %}
    </main>
</body>
</html>

shop/templates/courses.html
{% extends 'base.html' %}

{% block title %}All Courses{% endblock %}

{% block content %}
    <table class="table mt-5 table-bordered table-striped table-hover">
        <thead class="table-dark">
            <tr>
                <th>Title</th>
                <th>Category</th>
                <th>Price</th>
                <th>Students Quantity</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for course in courses %}
                <tr>
                    <td>{{course.title}}</td>
                    <td>{{course.category}}</td>
                    <td>{{course.price}}</td>
                    <td>{{course.students_qty}}</td>
                    <td>
                        <button class="btn btn-primary">Buy</button>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<nav class="navbar navbar-dark bg-dark ">
    <div class="container">
        <ul class="navbar-nav">
            <li>
                <a href={% url "shop:category"%} class="navbar-brand">All Categorys</a>
                <a href={% url "shop:courses"%} class="navbar-brand">All Courses Shop</a>
            </li>
        </ul>
        <span class="navbar-text">
            <a href="/admin/" class="me-2" target="_blank">Admin</a>
            <a href="/api/v1/" target="_blank">API</a>
        </span>
    </div>
</nav>
<main class="container">
    {% block content %}
    {% endblock %}
</main>
</body>
</html>

templates/shop/category.html
{% extends 'base.html' %}

{% block title %}All Categorys{% endblock %}

{% block content %}
<table class="table mt-5 table-bordered table-striped table-hover">
    <thead class="table-dark">
    <tr>
        <th>ID</th>
        <th>Title</th>
        <th>Creata pe Data de:</th>
    </tr>
    </thead>
    <tbody>
    {% for category in category %}
    <tr>
        <td>{{category.id}}</td>
        <td>
            <a href={% url "shop:category_selected" category.id %}>{{category.title}}</a>
        </td>
        <td>{{category.created_at}}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

templates/shop/category_selected.html
{% extends 'base.html' %}

{% block title %}Selected Courses By Category{% endblock %}

{% block content %}

<table class="table mt-5 table-bordered table-striped table-hover">
    <thead class="table-dark">
    <tr>
        <th>ID</th>
        <th>Category</th>
        <th>Title</th>
        <th>Price</th>
        <th>Students Quantity</th>
        <th>Buy Course</th>
    </tr>
    </thead>
    <tbody>

    {% for course in courses %}

    <tr>
        <td>{{course.id}}</td>
        <td>{{course.category}}</td>
        <td>
            <a href={% url "shop:course_selected" course.id %}>{{course.title}}</a>
        </td>
        <td>{{course.price}}</td>
        <td>{{course.students_qty}}</td>
        <td>
            <button class="btn btn-primary">Buy</button>
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

templates/shop/course_selected.html
{% extends 'base.html' %}

{% block title %}{{ course.title }}{% endblock %}

{% block content %}
<h1>{{ course.title }}</h1>
<h2>{{ course.category }}</h2>
<p>Price: {{ course.price }}</p>
<p>Student Quantity: {{ course.students_qty }}</p>
<button class="btn btn-primary">Buy</button>
{% endblock %}

templates/shop/courses.html
{% extends 'base.html' %}

{% block title %}All Courses{% endblock %}

{% block content %}
    <table class="table mt-5 table-bordered table-striped table-hover">
        <thead class="table-dark">
            <tr>
                <th>ID</th>
                <th>Title</th>
                <th>Category</th>
                <th>Price</th>
                <th>Students Quantity</th>
                <th>Buy Course</th>
            </tr>
        </thead>
        <tbody>
            {% for course in courses %}
                <tr>
                    <td>{{course.id}}</td>
                    <td>
                        <a href={% url "shop:course_selected" course.id %}>{{course.title}}</a>
                    </td>
                    <td>{{course.category}}</td>
                    <td>{{course.price}}</td>
                    <td>{{course.students_qty}}</td>
                    <td>
                        <button class="btn btn-primary">Buy</button>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}